#%RAML 1.0
title: Calculator-api
version: v1
protocols:
- HTTP
/addition:
  get:
    queryParameters:
      number1:
        required: true
        type: number
      number2:
        required: true
        type: number
    responses:
      200:
        body:
          application/json:
            example:
              {
               "result" : "addition is 8"
              }
      400:
         body:
          application/json:
            example:
              {
               "result" : "addition is 8"
              }

